package com.it2299.ffth.reincoast.dto;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
// Declare this class as entity so that Hibernate will know this is to be taken
// care of. Mapping configuration required in hibernate.cfg.xml.
@Table(name = "InboundTrans")
public class InboundTrans {

	@Id
	// Declare this attribute as primary key
	@GeneratedValue
	// Auto-increment value. Generated by Hibernate.
	@Column(name = "ID")
	// The corresponding column name in the table.
	private int id;

	@Column(name = "DonorType")
	private String donorType;

	@Column(name = "Donor")
	private String donor;

	@Column(name = "ReceiptNO")
	private int receiptNo;

	@Column(name = "Date")
	private Date date;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy="inboundTrans")
	private List<InboundItem> inboundItems;
	

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDonorType() {
		return donorType;
	}

	public void setDonorType(String donorType) {
		this.donorType = donorType;
	}

	public String getDonor() {
		return donor;
	}

	public void setDonor(String donor) {
		this.donor = donor;
	}

	public int getReceiptNo() {
		return receiptNo;
	}

	public void setReceiptNo(int receiptNo) {
		this.receiptNo = receiptNo;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public List<InboundItem> getInboundItems() {
		return inboundItems;
	}

	public void setInboundItems(List<InboundItem> inboundItems) {
		this.inboundItems = inboundItems;
	}

}
