package com.it2299.ffth.reincoast.dto;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.lucene.document.Field.Store;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.WordDelimiterFilterFactory;
import org.apache.solr.analysis.NGramFilterFactory;
import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.NumericField;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.bridge.builtin.DoubleBridge;

/**
 * @author kfwong
 * 
 *         There's no need for you to create any tables in your database, except
 *         an empty database itself. Once the entity class is properly
 *         annotated, Hibernate will execute appropriate query to persist the
 *         object and DB. Same as classes, you have to import the respective
 *         packages after you write the annotations. Import from
 *         javax.persistence package whenever you can. Certain extra features
 *         implemented by Hibernate will require you to import from
 *         org.hibernate package.
 */
@Entity
@Audited
@Indexed
@AnalyzerDef(name="productanalyzer",
		tokenizer = @TokenizerDef(factory = StandardTokenizerFactory.class),
		filters = {
			@TokenFilterDef(factory = LowerCaseFilterFactory.class),
			@TokenFilterDef(factory = SnowballPorterFilterFactory.class, params={
				@Parameter(name="language", value="English")
			})
})
// Declare this class as entity so that Hibernate will know this is to be taken
// care of. Mapping configuration required in hibernate.cfg.xml.
@Table(name = "PRODUCT")
// The table name that will be created upon persistence.
public class Product {
	@Id
	// Declare this attribute as primary key
	@GeneratedValue
	// Auto-increment value. Generated by Hibernate.
	@Column(name = "ID")
	// The corresponding column name in the table.
	private int id;

	@Column(name = "CODE")
	private String code;

	@Column(name = "NAME")
	@Field
	@Analyzer(definition = "productanalyzer")
	private String name;

	@Column(name = "DESCRIPTION")
	@Field
	@Analyzer(definition = "productanalyzer")
	private String description;

	@Column(name = "UNIT_OF_MEASURE")
	private String unitOfMeasure;

	@Column(name = "PRICE")
	@Field
	@NumericField
	private double price;

	@Column(name = "WEIGHT")
	@Field
	@NumericField
	private double weight;
	
	@Column(name = "QUANTITY", columnDefinition="int default 0")
	@Field
	@NumericField
	private int quantity;

	@Column(name = "CATEGORY")
	@Field
	@Analyzer(definition = "productanalyzer")
	private String category;

	@Column(name = "STATUS")
	private String status;

	@Column(name = "DATE_REGISTERED")
	private Date dateRegistered;

	@Column(name = "REGISTERED_BY")
	private String registeredBy;
	
	@Column(name = "IMAGE_URL")
	private String imageUrl;

	@OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.ALL, mappedBy="product")
	@IndexedEmbedded
	private List<ProductMeta> productMetas;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUnitOfMeasure() {
		return unitOfMeasure;
	}

	public void setUnitOfMeasure(String unitOfMeasure) {
		this.unitOfMeasure = unitOfMeasure;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public double getWeight() {
		return weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDateRegistered() {
		return dateRegistered;
	}

	public void setDateRegistered(Date dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	public String getRegisteredBy() {
		return registeredBy;
	}

	public void setRegisteredBy(String registeredBy) {
		this.registeredBy = registeredBy;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public List<ProductMeta> getProductMetas() {
		return productMetas;
	}

	public void setProductMetas(List<ProductMeta> productMetas) {
		this.productMetas = productMetas;
	}

}
